
    create table Budget (
        currentAmount float(53),
        id integer generated by default as identity,
        idCurrentStatus varchar(255),
        primary key (id)
    );

    create table Comunication (
        amount float(53),
        id integer generated by default as identity,
        idBudget integer,
        idCustomerContact integer,
        messageDate date,
        idStatus varchar(255),
        message varchar(255),
        primary key (id)
    );

    create table CUSTOMER (
        id integer generated by default as identity,
        address varchar(255),
        name varchar(255),
        phone varchar(255),
        vatnumber varchar(255),
        primary key (id)
    );

    create table CUSTOMER_CONTACT (
        id integer generated by default as identity,
        idCustomer integer,
        email varchar(255),
        name varchar(255) not null,
        observations varchar(255),
        phone varchar(255),
        primary key (id)
    );

    create table ROLES (
        rolename varchar(255) not null,
        primary key (rolename)
    );

    create table STATUS (
        statusName varchar(255) not null,
        primary key (statusName)
    );

    create table USERS (
        enabled boolean,
        expiryDateAccount date,
        expiryDateCredentials date,
        lockedAccount boolean,
        email varchar(255),
        fullname varchar(255),
        password varchar(255),
        username varchar(255) not null,
        primary key (username)
    );

    create table USERS_HAS_ROLES (
        User_username varchar(255) not null,
        roleSet_rolename varchar(255) not null,
        primary key (User_username, roleSet_rolename)
    );

    alter table if exists Budget 
       add constraint FK6nelshx4tjyn8vr9b1clpwl8 
       foreign key (idCurrentStatus) 
       references STATUS;

    alter table if exists Comunication 
       add constraint FK4d67j33wunxmr9vu6qulqic8h 
       foreign key (idCustomerContact) 
       references CUSTOMER_CONTACT;

    alter table if exists Comunication 
       add constraint FKebxjxvoqbx2x51sjjnthh7won 
       foreign key (idBudget) 
       references Budget;

    alter table if exists Comunication 
       add constraint FKse5grlm95v9tqfk5qipjxjxex 
       foreign key (idStatus) 
       references STATUS;

    alter table if exists CUSTOMER_CONTACT 
       add constraint FK3x9hlfbvhpkca4avlhe6dt7f7 
       foreign key (idCustomer) 
       references CUSTOMER;

    alter table if exists USERS_HAS_ROLES 
       add constraint FK40jy793cg5kbts0087cm4engd 
       foreign key (roleSet_rolename) 
       references ROLES;

    alter table if exists USERS_HAS_ROLES 
       add constraint FKfy7x7il32rr6kyeos1va1fvh5 
       foreign key (User_username) 
       references USERS;
